name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Cron Update
    - cron: "0 1,3,5,7,9-11,13,15-23 2,4,6,8,10,12,14,16,18,20,22,24-31 * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LINES_OF_CODE: "True"
